name = "wallpect"
compatibility_date = "2026-07-18"
workers_dev = true
preview_urls = true

[[routes]]
pattern = "wallpect.k-y.cc/*"
zone_name = "k-y.cc"

[assets]
directory = "./dist"
not_found_handling = "single-page-application"
